
import { Trainer, Membership, Product, Language, Review } from './types';

// Updated to a gender-neutral silhouette as requested
export const DEFAULT_PROFILE_IMAGE = "https://upload.wikimedia.org/wikipedia/commons/2/2c/Default_pfp.svg";

export const getTrainers = (lang: Language): Trainer[] => {
  const isBg = lang === 'bg';
  return [
    {
      id: '1',
      name: isBg ? 'Иван Петров' : 'Ivan Petrov',
      specialty: isBg ? 'Силови тренировки' : 'Strength Training',
      price: 15,
      image: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?q=80&w=400&auto=format&fit=crop',
      phone: '+359 88 123 4567',
      bio: isBg 
        ? 'С над 10 години опит в бодибилдинга, Иван специализира в изграждане на мускулна маса и силова издръжливост. Неговата философия е "дисциплина над мотивация".'
        : 'With over 10 years of bodybuilding experience, Ivan specializes in muscle hypertrophy and strength endurance. His philosophy is "discipline over motivation".',
      availability: ['08:00', '09:00', '10:00', '14:00', '15:00', '16:00'],
      languages: ['Bulgarian', 'English']
    },
    {
      id: '2',
      name: isBg ? 'Мария Иванова' : 'Maria Ivanova',
      specialty: isBg ? 'Йога и Пилатес' : 'Yoga & Pilates',
      price: 15,
      image: 'https://images.unsplash.com/photo-1518611012118-296072bb5fe9?q=80&w=400&auto=format&fit=crop',
      phone: '+359 88 234 5678',
      bio: isBg
        ? 'Мария комбинира древни йога практики със съвременни методи за възстановяване. Тя помага на клиентите да намерят баланс между тялото и ума.'
        : 'Maria combines ancient yoga practices with modern recovery methods. She helps clients find balance between body and mind.',
      availability: ['07:00', '11:00', '12:00', '17:00', '18:00'],
      languages: ['Bulgarian', 'English', 'Russian']
    },
    {
      id: '3',
      name: isBg ? 'Елена Костова' : 'Elena Kostova',
      specialty: isBg ? 'Кросфит' : 'Crossfit',
      price: 15,
      image: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?q=80&w=400&auto=format&fit=crop',
      phone: '+359 88 345 6789',
      bio: isBg
        ? 'Бивш състезател по лека атлетика, Елена води високоинтензивни тренировки, които предизвикват границите ви. Експерт по функционален фитнес.'
        : 'A former track and field athlete, Elena leads high-intensity workouts that push your limits. Expert in functional fitness.',
      availability: ['09:00', '10:00', '11:00', '15:00', '19:00'],
      languages: ['Bulgarian', 'English']
    }
  ];
};

export const getMemberships = (lang: Language): Membership[] => {
  const isBg = lang === 'bg';
  return [
    {
      id: 'single',
      name: isBg ? 'Еднократна тренировка' : 'Single Visit',
      price: '7.00',
      unit: isBg ? 'ПОСЕЩЕНИЕ' : 'VISIT',
      features: isBg 
        ? ['Достъп до цялото оборудване', 'Ползване на шкафче', 'Безплатен Wi-Fi'] 
        : ['Access to all equipment', 'Locker access', 'Free Wi-Fi'],
    },
    {
      id: 'unlimited_women',
      name: isBg ? 'Карта Жени (30 дни)' : 'Women Unlimited (30d)',
      price: '70.00',
      unit: isBg ? 'МЕСЕЦ' : 'MONTH',
      features: isBg 
        ? ['Неограничени посещения', 'Професионално оборудване', 'Валидност 30 дни'] 
        : ['Unlimited visits', 'Professional equipment', 'Valid for 30 days'],
    },
    {
      id: 'unlimited_men',
      name: isBg ? 'Карта Мъже (30 дни)' : 'Men Unlimited (30d)',
      price: '90.00',
      unit: isBg ? 'МЕСЕЦ' : 'MONTH',
      features: isBg 
        ? ['Неограничени посещения', 'Професионално оборудване', 'Валидност 30 дни'] 
        : ['Unlimited visits', 'Professional equipment', 'Valid for 30 days'],
      isPopular: true
    }
  ];
};

export const getProducts = (lang: Language): Product[] => {
  const isBg = lang === 'bg';
  return [
    { 
      id: 'prog1', 
      name: isBg ? 'Индивидуална програма' : 'Individual Program', 
      price: 50.00, 
      category: isBg ? 'Програми' : 'Programs', 
      image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=400&auto=format&fit=crop',
      description: isBg 
        ? 'Персонализиран тренировъчен план, изготвен според вашите цели.'
        : 'A personalized training plan tailored to your goals.'
    },
    { 
      id: 'p1', 
      name: 'ON Gold Standard Whey 2.27kg', 
      price: 135.00, 
      category: isBg ? 'Добавки' : 'Supplements', 
      image: 'https://content.optimumnutrition.com/i/on/on-gold-standard-100-whey_Image_01?locale=en-us,en-gb,*&layer0=$MAIN$',
      description: isBg ? 'Най-продаваният протеин в света.' : 'The world\'s best-selling whey protein.'
    },
    { 
      id: 'p4', 
      name: 'Creatine Monohydrate 500g', 
      price: 45.00, 
      category: isBg ? 'Добавки' : 'Supplements', 
      image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&q=80&w=800',
      description: isBg ? 'За сила и издръжливост.' : 'For strength and endurance.'
    },
  ];
};

export const getReviews = (lang: Language): Review[] => {
  const isBg = lang === 'bg';
  return [
    { id: 'r1', author: isBg ? 'Георги Димитров' : 'Georgi Dimitrov', rating: 5, text: isBg ? 'Най-добрата зала във Варна! Локацията е супер.' : 'Best gym in Varna! Great location.', time: isBg ? 'преди 2 седмици' : '2 weeks ago', avatar: 'G' },
    { id: 'r2', author: isBg ? 'Александра Н.' : 'Aleksandra N.', rating: 5, text: isBg ? 'Много чиста и подредена зала.' : 'Very clean and tidy gym.', time: isBg ? 'преди 1 месец' : '1 month ago', avatar: 'A' },
  ];
};

export const getTrainerReviews = (trainerId: string, lang: Language): Review[] => {
  const isBg = lang === 'bg';
  const reviews: Review[] = [
    { 
      id: `tr1-${trainerId}`, 
      trainerId,
      author: isBg ? 'Михаил Т.' : 'Michael T.', 
      rating: 5, 
      text: isBg ? 'Изключителен професионалист! Помогна ми да кача 5кг мускулна маса за 2 месеца.' : 'Exceptional professional! Helped me gain 5kg of muscle mass in 2 months.', 
      time: isBg ? 'преди 3 дни' : '3 days ago', 
      avatar: 'M' 
    },
    { 
      id: `tr2-${trainerId}`, 
      trainerId,
      author: isBg ? 'Виктория С.' : 'Victoria S.', 
      rating: 5, 
      text: isBg ? 'Тренировките са тежки, но резултатите си заслужават. Препоръчвам горещо!' : 'Workouts are tough but results are worth it. Highly recommend!', 
      time: isBg ? 'преди 1 седмица' : '1 week ago', 
      avatar: 'V' 
    }
  ];
  return reviews;
};

export const TRANSLATIONS = {
  bg: {
    home: 'Начало',
    about: 'За нас',
    booking: 'Резервация',
    memberships: 'Карти',
    shop: 'Магазин',
    admin: 'Web Admin',
    management: 'Management',
    contact: 'Контакти',
    login: 'Вход',
    register: 'Регистрация',
    logout: 'Изход',
    myBookings: 'Моите часове',
    location: 'Локация',
    address: 'ЛевскиПриморски, ул. „Студентска“ 1 а',
    stop: '9010 Варна',
    connect: 'Свържи се',
    rights: '© 2024 CLASSFIT VARNA',
    nav: 'Навигация',
    gymDesc: 'Професионална фитнес база във Варна. Дисциплина и резултати.',
    gymPhone: '+359 88 343 0184',
    transform: 'ТРАНСФОРМИРАЙ',
    yourself: 'СЕБЕ СИ',
    motivation: 'Вашият път към съвършенството започва тук.',
    joinMovement: 'Стани част от ClassFit',
    bookNow: 'Запиши час',
    eliteBase: 'Елитна База Варна',
    expertise: 'Експертиза',
    expertiseDesc: 'Треньори, фокусирани върху вашия прогрес.',
    community: 'Общност',
    communityDesc: 'Среда от мотивирани хора.',
    locationDesc: 'Намираме се в ЛевскиПриморски, ул. Студентска 1а.',
    pushBoundaries: 'ПРЕМИНЕТЕ ГРАНИЦИТЕ СИ',
    pushDesc: 'В ClassFit всяка тренировка е инвестиция в бъдещото ти аз. Базата ни е оборудвана с висок клас уреди.',
    readyLevel: 'ГОТОВИ ЛИ СТЕ ЗА СЛЕДВАЩОТО НИВО?',
    joinClassfit: 'ЕЛА В CLASSFIT',
    features: ['Топ Оборудване', 'Лични Треньори', 'Добавки', 'Общност'],
    reviewsTitle: 'Отзиви',
    reviewsSubtitle: 'Какво казват нашите членове',
    viewOnGoogle: 'Виж в Google Maps',
    googleRating: 'Google Рейтинг',
    basedOn: 'Базирано на 120+ отзива',
    selectTrainer: 'Избери треньор',
    team: 'Екип',
    perSession: 'лв / тренировка',
    trainerCalendar: 'График',
    availableSlots: 'Свободни часове',
    confirmText: 'Нужно е потвърждение от треньора',
    total: 'Общо',
    finalize: 'Финализиране',
    enterDetails: 'Въведете данни за контакт.',
    name: 'Име',
    phone: 'Телефон',
    yourName: 'Вашето Име',
    confirmBooking: 'Потвърди резервация',
    haveAccount: 'Имате акаунт?',
    loginProfile: 'Вход в профил',
    chooseTrainer: 'Изберете треньор',
    seeCalendar: 'За да видите графика',
    reqSent: 'Заявката е изпратена!',
    newBooking: 'Нова резервация',
    checkEmail: 'Вижте имейла си за потвърждение.',
    lateOrCancel: 'За отмяна на час:',
    ourDna: 'Нашето ДНК',
    weAre: 'Ние сме ClassFit.',
    aboutDesc: 'ClassFit е роден от страстта към съвършенството. Намираме се във Варна и предоставяме безкомпромисно качество.',
    mission: 'Мисия',
    missionDesc: 'Да превърнем всяка тренировка в стъпка към пълното ви преобразяване.',
    values: 'Ценности',
    valuesDesc: 'Дисциплина и подкрепа за всеки член.',
    vision: 'Визия',
    visionDesc: 'Да бъдем еталон за иновации във фитнес индустриата на Варна.',
    beLegendary: 'Бъди Легенда.',
    choosePower: 'Изберете вашата карта.',
    mostPopular: 'Най-популярна',
    month: 'Месец',
    signUp: 'Запиши се',
    payAtDesk: 'Плащане на рецепция',
    learnMore: 'Научи повече',
    store: 'Classfit Магазин',
    premiumProducts: 'Премиум продукти за най-добрите.',
    catAll: 'Всички',
    catSupplements: 'Добавки',
    catGear: 'Екипировка',
    catPrograms: 'Програми',
    ableToPayAtDesk: 'Плащане на място',
    adminPanel: 'Админ Панел',
    welcomeAdmin: 'Контролен панел.',
    tabOverview: 'Обзор',
    tabAnalysis: 'Финанси',
    tabBookings: 'Активни',
    tabHistory: 'История',
    tabUsers: 'Профили',
    tabMessages: 'Съобщения',
    tabRecruitment: 'Кандидатури',
    tabModeration: 'Модерация',
    registry: 'Регистър',
    totalIncome: 'Приход',
    genBy: 'От',
    completedWorkouts: 'тренировки',
    financialAnalysis: 'Отчет',
    trainer: 'Инструктор',
    workouts: 'Брой',
    cash: 'Кеш',
    card: 'Карта',
    totalSum: 'Общо',
    totalTotal: 'Тотал',
    allBookings: 'Текущи',
    historyBookings: 'Архив',
    allUsers: 'Акаунти',
    allMessages: 'Входящи Съобщения',
    client: 'Клиент',
    details: 'Детайли',
    status: 'Статус',
    action: 'Действие',
    role: 'Роля',
    joined: 'Дата',
    deleteUser: 'Изтрий',
    deleteBooking: 'Изтрий',
    noRecords: 'Няма записи.',
    confirm: 'Потвърди',
    cancel: 'Откажи',
    finish: 'Приключи',
    markFinished: 'Маркирай като платена',
    accessDenied: 'Нямате достъп',
    accessDeniedDesc: 'Само за администратори.',
    clubMember: 'Член',
    hello: 'Здравей',
    welcomeBackUser: 'Добре дошъл обратно.',
    noBookings: 'Нямате часове.',
    makeFirst: 'Запишете първия си час',
    sure: 'Сигурни ли сте?',
    cancelReq: 'Отказ',
    saveToCalendar: 'Добави в Календар',
    trainerPhoneLabel: 'Треньор',
    gymPhoneLabel: 'Зала',
    email: 'Имейл',
    password: 'Парола',
    nameSurname: 'Име и Фамилия',
    createAccount: 'Регистрация',
    loginBtn: 'Влез',
    welcomeBack: 'Добре дошли в ClassFit',
    startTrans: 'Започнете днес',
    invalidCreds: 'Грешен имейл или парола.',
    emailTaken: 'Имейлът е заети.',
    noAccount: 'Нямате акаунт?',
    yesAccount: 'Имате акаунт?',
    registerHere: 'Регистрация',
    loginHere: 'Влез тук',
    statusPending: 'Изчаква',
    statusConfirmed: 'Потвърден',
    statusCancelled: 'Отказан',
    statusCompleted: 'Платен',
    statusTrainerCompleted: 'Очаква плащане',
    getInTouch: 'Свържете се с нас',
    sendMessage: 'Изпрати съобщение',
    message: 'Съобщение',
    sender: 'Подател',
    received: 'Получено',
    deleteMsg: 'Изтрий',
    reply: 'Отговор',
    subject: 'Тема',
    workingHours: 'Работно време',
    monFri: 'Пон - Пет',
    satSun: 'Съб - Нед',
    sendSuccess: 'Съобщението е изпратено успешно!',
    joinTeam: 'Кариера',
    joinTeamTitle: 'Стани част от екипа',
    joinTeamDesc: 'Развивайте бизнеса си в ClassFit.',
    trainerRegistration: 'Регистрация за треньори',
    roleUser: 'Потребител',
    roleTrainer: 'Инструктор',
    roleAdmin: 'Web Admin',
    roleManagement: 'Management',
    roleTrainerPending: 'Чакащ',
    changeRole: 'Промяна',
    emailConfirmMsg: 'Потвърждение за резервацията е изпратено на:',
    trainerReviewMsg: 'Треньорът ще прегледа вашата заявка и ще я потвърди скоро.',
    trainerFullName: 'Пълно име',
    trainerEmail: 'Професионален имейл',
    trainerPassword: 'Парола',
    trainerPhone: 'Телефон за връзка',
    trainerSpecialty: 'Основна дисциплина',
    trainerExperience: 'Години опит',
    trainerCerts: 'Сертификати и образование',
    trainerSocial: 'Социален профил (IG/LI)',
    trainerMotivation: 'Защо искате да се присъедините към ClassFit?',
    trainerSubmit: 'Изпрати заявка',
    trainerReviewHours: 'До 48 часа за преглед',
    trainerLanguagesSpoken: 'Говорими езици',
    identityAndAccess: 'Идентичност и достъп',
    expertiseAndExperience: 'Експертиза и опит',
    motivationAndReach: 'Мотивация и обхват',
    years: 'Години',
    eliteTeam: 'ЕЛИТНИЯ ЕКИП',
    joinThe: 'СТАНИ ЧАСТ ОТ',
    varnaProfessionals: 'Търсим най-добрите професионалисти във Варна. Развивайте кариерата си при нас.',
    coachPortal: 'Портал за кандидатстване на треньори',
    professionalDetails: 'ПРОФЕСИОНАЛНИ ДЕТАЙЛИ',
    coachPhilosophy: 'Разкажете ни за вашата експертиза и защо мястото ви е в ClassFit.',
    applicationFiled: 'ЗАЯВКАТА Е ПРИЕТА',
    pendingReviewMsg: 'Профилът ви беше създаден успешно със статус "Изчакващ". Екипът на ClassFit ще прегледа вашата експертиза и ще се свърже с вас за интервю.',
    returnToBase: 'Към началната страница',
    reviewModalTitle: 'ClassFit биха се радвали да разберат за твоя опит от тренировката с',
    reviewModalSubtitle: 'Твоят откровен отзив помага на нашата общност!',
    yourExperience: 'Твоето преживяване',
    submitFeedback: 'Изпрати отзив',
    polishWithAi: 'Полирай с AI',
    feedbackProvided: 'Отзивът е изпратен',
    leaveReview: 'Остави отзив',
    myWorkouts: 'Моите тренировки',
    registryTitle: 'Регистър на тренировките',
    interactionRequired: 'Необходим е отзив за приключените сесии',
    profileSettings: 'Настройки на профила',
    editIdentity: 'Редактирай идентичността',
    coachRegistry: 'Регистър на треньори'
  },
  en: {
    home: 'Home',
    about: 'About',
    booking: 'Booking',
    memberships: 'Memberships',
    shop: 'Shop',
    admin: 'Web Admin',
    management: 'Management',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    myBookings: 'My Sessions',
    location: 'Location',
    address: 'ЛевскиПриморски, ул. „Студентска“ 1 а',
    stop: '9010 Varna',
    connect: 'Connect',
    rights: '© 2024 CLASSFIT VARNA',
    nav: 'Navigation',
    gymDesc: 'Professional fitness in Varna. Discipline & Results.',
    gymPhone: '+359 88 343 0184',
    transform: 'TRANSFORM',
    yourself: 'YOURSELF',
    motivation: 'Your path to perfection starts here.',
    joinMovement: 'Join ClassFit',
    bookNow: 'Book Session',
    eliteBase: 'Varna Elite Base',
    expertise: 'Expertise',
    expertiseDesc: 'Coaches focused on your growth.',
    community: 'Community',
    communityDesc: 'Motivated environment.',
    locationDesc: 'Located in ЛевскиПриморски, ул. Студентска 1а.',
    pushBoundaries: 'PUSH YOUR BOUNDARIES',
    pushDesc: 'Every workout is an investment. Our facility is top-tier.',
    readyLevel: 'READY FOR THE NEXT LEVEL?',
    joinClassfit: 'JOIN CLASSFIT',
    features: ['Pro Equipment', 'Personal Trainers', 'Supplements', 'Community'],
    reviewsTitle: 'Reviews',
    reviewsSubtitle: 'What our members say',
    viewOnGoogle: 'Google Maps',
    googleRating: 'Google Rating',
    basedOn: '120+ reviews',
    selectTrainer: 'Select Trainer',
    team: 'Team',
    perSession: 'lv / session',
    trainerCalendar: 'Schedule',
    availableSlots: 'Available slots',
    confirmText: 'Requires coach confirmation',
    total: 'Total',
    finalize: 'Finalize',
    enterDetails: 'Enter contact details.',
    name: 'Name',
    phone: 'Phone',
    yourName: 'Your Name',
    confirmBooking: 'Confirm Booking',
    haveAccount: 'Have an account?',
    loginProfile: 'Login',
    chooseTrainer: 'Select trainer',
    seeCalendar: 'To see schedule',
    reqSent: 'Request Sent!',
    newBooking: 'New Booking',
    checkEmail: 'Check your email.',
    lateOrCancel: 'To cancel a session:',
    ourDna: 'Our DNA',
    weAre: 'We are ClassFit.',
    aboutDesc: 'Born from a passion for perfection. Based in Varna.',
    mission: 'Mission',
    missionDesc: 'Every workout a step to transformation.',
    values: 'Values',
    valuesDesc: 'Discipline and support.',
    vision: 'Vision',
    visionDesc: 'Innovating Varna fitness.',
    beLegendary: 'Be Legendary.',
    choosePower: 'Choose your card.',
    mostPopular: 'Most Popular',
    month: 'Month',
    signUp: 'Sign Up',
    payAtDesk: 'Pay at Desk',
    learnMore: 'Learn More',
    store: 'Classfit Store',
    premiumProducts: 'Premium products.',
    catAll: 'All',
    catSupplements: 'Supplements',
    catGear: 'Gear',
    catPrograms: 'Programs',
    ableToPayAtDesk: 'Pay at gym',
    adminPanel: 'Admin Panel',
    welcomeAdmin: 'Control center.',
    tabOverview: 'Overview',
    tabAnalysis: 'Finance',
    tabBookings: 'Active',
    tabHistory: 'History',
    tabUsers: 'Users',
    tabMessages: 'Messages',
    tabRecruitment: 'Applications',
    tabModeration: 'Moderation',
    registry: 'Registry',
    totalIncome: 'Income',
    genBy: 'By',
    completedWorkouts: 'sessions',
    financialAnalysis: 'Analysis',
    trainer: 'Gym Coach',
    workouts: 'Count',
    cash: 'Cash',
    card: 'Card',
    totalSum: 'Total',
    totalTotal: 'Total',
    allBookings: 'Current',
    historyBookings: 'Archive',
    allUsers: 'Accounts',
    allMessages: 'Inbox Messages',
    client: 'Client',
    details: 'Details',
    status: 'Status',
    action: 'Action',
    role: 'Role',
    joined: 'Joined',
    deleteUser: 'Delete',
    deleteBooking: 'Delete',
    noRecords: 'No records.',
    confirm: 'Confirm',
    cancel: 'Cancel',
    finish: 'Finish',
    markFinished: 'Mark Paid',
    accessDenied: 'Access Denied',
    accessDeniedDesc: 'Admins only.',
    clubMember: 'Member',
    hello: 'Hello',
    welcomeBackUser: 'Welcome back.',
    noBookings: 'No active sessions.',
    makeFirst: 'Book your first session',
    sure: 'Are you sure?',
    cancelReq: 'Cancel',
    saveToCalendar: 'Add to Calendar',
    trainerPhoneLabel: 'Trainer',
    gymPhoneLabel: 'Gym',
    email: 'Email',
    password: 'Password',
    nameSurname: 'Full Name',
    createAccount: 'Sign Up',
    loginBtn: 'Login',
    welcomeBack: 'Welcome to ClassFit',
    startTrans: 'Start today',
    invalidCreds: 'Wrong email or password.',
    emailTaken: 'Email already taken.',
    noAccount: 'No account?',
    yesAccount: 'Have an account?',
    registerHere: 'Sign Up',
    loginHere: 'Login here',
    statusPending: 'Pending',
    statusConfirmed: 'Confirmed',
    statusCancelled: 'Cancelled',
    statusCompleted: 'Completed',
    statusTrainerCompleted: 'Awaiting Payment',
    getInTouch: 'Get in touch',
    sendMessage: 'Send Message',
    message: 'Message',
    sender: 'Sender',
    received: 'Received',
    deleteMsg: 'Delete',
    reply: 'Reply',
    subject: 'Subject',
    workingHours: 'Working Hours',
    monFri: 'Mon - Fri',
    satSun: 'Sat - Sun',
    sendSuccess: 'Message sent successfully!',
    joinTeam: 'Career',
    joinTeamTitle: 'Join the team',
    joinTeamDesc: 'Grow your business at ClassFit.',
    trainerRegistration: 'Coach Registration',
    roleUser: 'User',
    roleTrainer: 'Gym Coach',
    roleAdmin: 'Web Admin',
    roleManagement: 'Management',
    roleTrainerPending: 'Pending',
    changeRole: 'Change',
    emailConfirmMsg: 'A confirmation has been sent to:',
    trainerReviewMsg: 'Your selected trainer will review and confirm your session shortly.',
    trainerFullName: 'Full Name',
    trainerEmail: 'Professional Email',
    trainerPassword: 'Password',
    trainerPhone: 'Contact Phone',
    trainerSpecialty: 'Primary Discipline',
    trainerExperience: 'Years of Experience',
    trainerCerts: 'Certs & Education',
    trainerSocial: 'Social Link (IG/LI)',
    trainerMotivation: 'Why do you want to join ClassFit?',
    trainerSubmit: 'Submit Application',
    trainerReviewHours: '48h Review Policy',
    trainerLanguagesSpoken: 'Languages Spoken',
    identityAndAccess: 'Identity & Access',
    expertiseAndExperience: 'Expertise & Experience',
    motivationAndReach: 'Motivation & Reach',
    years: 'Years',
    eliteTeam: 'ELITE TEAM',
    joinThe: 'JOIN THE',
    varnaProfessionals: 'We are looking for the absolute best professionals in Varna. Grow your career with us.',
    coachPortal: 'Coach Application Portal',
    professionalDetails: 'PROFESSIONAL DETAILS',
    coachPhilosophy: 'Tell us about your expertise and why you belong at ClassFit.',
    applicationFiled: 'APPLICATION FILED',
    pendingReviewMsg: 'Your profile has been successfully created with pending status. The ClassFit team will review your expertise and contact you for an interview.',
    returnToBase: 'Return to Base',
    reviewModalTitle: 'ClassFit would love to know about your experience training with',
    reviewModalSubtitle: 'Your honest feedback helps our community!',
    yourExperience: 'Your Experience',
    submitFeedback: 'Submit Feedback',
    polishWithAi: 'Polish with AI',
    feedbackProvided: 'Feedback Provided',
    leaveReview: 'Leave a Review',
    myWorkouts: 'My Workouts',
    registryTitle: 'Workout Registry',
    interactionRequired: 'Feedback required for completed sessions',
    profileSettings: 'Profile Settings',
    editIdentity: 'Edit Identity',
    coachRegistry: 'Coach Registry'
  }
};
